name: form_builder_map_field
description: Map Input Field for flutter_form_builder package. Used to select coodinates on a map.
version: 0.0.1
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/form_builder_map_field

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^3.8.1
  google_maps_flutter: ^0.5.25+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
